name: ci

on: push

jobs:
  build_docker_image:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        image_subdir: ["quant_env"]

    steps:
    - uses: actions/checkout@v2

    - name: build image
      run: |
        PROJECT_DIR=$(pwd)
        cd ${{ matrix.image_subdir }}
        ls 
        docker build -t ${{ matrix.image_subdir }} .
        

